#
#           Project: pseudotv-plex         
#           Author: Dan Ferguson (dan.ferguson11@outlook.com)
#           Repository: https://gitlab.com/DEFENDORe/pseudotv-plex
#

# Server Settings
HOST: 127.0.0.1 # PseudoTV Host
PORT: 8000      # PseudoTV Port

# PLEX SERVER DETAILS
PLEX_OPTIONS:
  hostname: 127.0.0.1
  port: 32400
  # Since we're storing credentials, you might want to muck around with file 
  # permissions to prevent this file from being opened by anyone all willy nilly.
  username: your-plex-username
  password: your-plex-password

# Setup your muxer of choice. Either VLC or FFMPEG.
MUXER: ffmpeg
FFMPEG_OPTIONS:
  PATH: C:\ffmpeg-20200328-3362330-win64-static\bin\ffmpeg.exe # path to ffmpeg
  PREBUFFER: true # transmux entire program as fast as possible... Set false to stream "live" (ffmpeg -re ...)
VLC_OPTIONS:
  PATH: C:\Program Files\VideoLAN\VLC\vlc.exe # path to vlc
  PORT: 8001    # VLC will host a http server to serve mpegts stream
  DELAY: 1000   # milliseconds - wait 1 second cause VLC can be a piece of shit
  HIDDEN: true  # hide the vlc session

# Spoofed HDHomeRun Tuner Settings
HDHOMERUN_OPTIONS:
  AUTODISCOVERY: false  # Enable the finicky as fuck ssdp broadcaster.
  ENABLED: true         # Disable the HDHR tuner altogether if using xTeVe

# Specify how much EPG information to store in the XMLTV file
EPG_CACHE: 12 # hrs
# Specify how often to refresh epg
# NOTE: "shuffle"d playlists will get reshuffled on every update, it'd be a good idea to increase this to prevent pissing off users...
EPG_UPDATE: 20 # mins (0 = disable updating)

# Plex Automagic (if you host separate Plex Servers for your LiveTV and Playlists, you should disable these..)
PLEX_AUTO_REFRESH_GUIDE: true     # Refresh Plex DVR automatically
PLEX_AUTO_REMAP_CHANNELS: true    # Map/Remap Plex DVR Channels automatically

# Generated Files...
XMLTV_FILE: ./xmltv.xml   # the XMLTV file to import into Plex, or xTeVe
M3U_FILE: ./channels.m3u  # a M3U file containing channel lineup. Useful for xTeVe or viewing with external player.

# The first word in a playlists summary must match this for the playlist to be deemed a channel.
PLEX_PLAYLIST_IDENTIFIER: pseudotv

# X-Plex-Session-Identifier Header    Used for identifing transcoding session in Plex.
# Must be unique if running multiple instances of pseudotv-plex.
# Don't know how the fuck Plex generates them but they gotta be valid or else Plex will reject the request.
# This one was fetched with Chrome Dev Tools..
# DO NOT CHANGE UNLESS YOU KNOW WHATS UP... SHIT COULD/PROBABLY WILL BREAK. 
PLEX_SESSION_ID: 6fooaniy59s3hqqhqyn21xti